---
version: "2"

formatters:
  enable:
    - gofumpt
    - gci

linters:
  default: none
  enable:
    - copyloopvar
    - dupword
    - errcheck
    - govet
    - ineffassign
    - intrange
    - misspell
    - staticcheck
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 3m
  build-tags:
    - testtools
  modules-download-mode: readonly

output:
  sort-order:
    - file
