before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  # Library doesn't need to be built
  - skip: true
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
sboms:
  - documents:
      - bom.json
    artifacts: any
    cmd: cyclonedx-gomod
    args: [ "mod", "-licenses", "-std", "-json", "-output", "$document", "../" ]
