//go:build testtools

// Code generated by MockGen. DO NOT EDIT.
// Source: go.openfeature.dev/openfeature/v2 (interfaces: clientEvent,evaluationImpl,Hook,FeatureProvider,StateHandler,Tracker)
//
// Generated by this command:
//
//	mockgen -destination=interfaces_mock.go -package=openfeature -build_constraint=testtools -mock_names=FeatureProvider=MockProvider go.openfeature.dev/openfeature/v2 clientEvent,evaluationImpl,Hook,FeatureProvider,StateHandler,Tracker
//

// Package openfeature is a generated GoMock package.
package openfeature

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockclientEvent is a mock of clientEvent interface.
type MockclientEvent struct {
	ctrl     *gomock.Controller
	recorder *MockclientEventMockRecorder
	isgomock struct{}
}

// MockclientEventMockRecorder is the mock recorder for MockclientEvent.
type MockclientEventMockRecorder struct {
	mock *MockclientEvent
}

// NewMockclientEvent creates a new mock instance.
func NewMockclientEvent(ctrl *gomock.Controller) *MockclientEvent {
	mock := &MockclientEvent{ctrl: ctrl}
	mock.recorder = &MockclientEventMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockclientEvent) EXPECT() *MockclientEventMockRecorder {
	return m.recorder
}

// AddClientHandler mocks base method.
func (m *MockclientEvent) AddClientHandler(clientName string, t EventType, c EventCallback) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddClientHandler", clientName, t, c)
}

// AddClientHandler indicates an expected call of AddClientHandler.
func (mr *MockclientEventMockRecorder) AddClientHandler(clientName, t, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddClientHandler", reflect.TypeOf((*MockclientEvent)(nil).AddClientHandler), clientName, t, c)
}

// RemoveClientHandler mocks base method.
func (m *MockclientEvent) RemoveClientHandler(name string, t EventType, c EventCallback) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveClientHandler", name, t, c)
}

// RemoveClientHandler indicates an expected call of RemoveClientHandler.
func (mr *MockclientEventMockRecorder) RemoveClientHandler(name, t, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveClientHandler", reflect.TypeOf((*MockclientEvent)(nil).RemoveClientHandler), name, t, c)
}

// State mocks base method.
func (m *MockclientEvent) State(domain string) State {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "State", domain)
	ret0, _ := ret[0].(State)
	return ret0
}

// State indicates an expected call of State.
func (mr *MockclientEventMockRecorder) State(domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "State", reflect.TypeOf((*MockclientEvent)(nil).State), domain)
}

// MockevaluationImpl is a mock of evaluationImpl interface.
type MockevaluationImpl struct {
	ctrl     *gomock.Controller
	recorder *MockevaluationImplMockRecorder
	isgomock struct{}
}

// MockevaluationImplMockRecorder is the mock recorder for MockevaluationImpl.
type MockevaluationImplMockRecorder struct {
	mock *MockevaluationImpl
}

// NewMockevaluationImpl creates a new mock instance.
func NewMockevaluationImpl(ctrl *gomock.Controller) *MockevaluationImpl {
	mock := &MockevaluationImpl{ctrl: ctrl}
	mock.recorder = &MockevaluationImplMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockevaluationImpl) EXPECT() *MockevaluationImplMockRecorder {
	return m.recorder
}

// AddHandler mocks base method.
func (m *MockevaluationImpl) AddHandler(eventType EventType, callback EventCallback) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddHandler", eventType, callback)
}

// AddHandler indicates an expected call of AddHandler.
func (mr *MockevaluationImplMockRecorder) AddHandler(eventType, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddHandler", reflect.TypeOf((*MockevaluationImpl)(nil).AddHandler), eventType, callback)
}

// AddHooks mocks base method.
func (m *MockevaluationImpl) AddHooks(hooks ...Hook) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range hooks {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "AddHooks", varargs...)
}

// AddHooks indicates an expected call of AddHooks.
func (mr *MockevaluationImplMockRecorder) AddHooks(hooks ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddHooks", reflect.TypeOf((*MockevaluationImpl)(nil).AddHooks), hooks...)
}

// ForEvaluation mocks base method.
func (m *MockevaluationImpl) ForEvaluation(clientName string) (FeatureProvider, []Hook, EvaluationContext) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForEvaluation", clientName)
	ret0, _ := ret[0].(FeatureProvider)
	ret1, _ := ret[1].([]Hook)
	ret2, _ := ret[2].(EvaluationContext)
	return ret0, ret1, ret2
}

// ForEvaluation indicates an expected call of ForEvaluation.
func (mr *MockevaluationImplMockRecorder) ForEvaluation(clientName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForEvaluation", reflect.TypeOf((*MockevaluationImpl)(nil).ForEvaluation), clientName)
}

// GetClient mocks base method.
func (m *MockevaluationImpl) GetClient() *Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient")
	ret0, _ := ret[0].(*Client)
	return ret0
}

// GetClient indicates an expected call of GetClient.
func (mr *MockevaluationImplMockRecorder) GetClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockevaluationImpl)(nil).GetClient))
}

// GetHooks mocks base method.
func (m *MockevaluationImpl) GetHooks() []Hook {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHooks")
	ret0, _ := ret[0].([]Hook)
	return ret0
}

// GetHooks indicates an expected call of GetHooks.
func (mr *MockevaluationImplMockRecorder) GetHooks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHooks", reflect.TypeOf((*MockevaluationImpl)(nil).GetHooks))
}

// GetNamedClient mocks base method.
func (m *MockevaluationImpl) GetNamedClient(clientName string) *Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamedClient", clientName)
	ret0, _ := ret[0].(*Client)
	return ret0
}

// GetNamedClient indicates an expected call of GetNamedClient.
func (mr *MockevaluationImplMockRecorder) GetNamedClient(clientName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamedClient", reflect.TypeOf((*MockevaluationImpl)(nil).GetNamedClient), clientName)
}

// GetNamedProviderMetadata mocks base method.
func (m *MockevaluationImpl) GetNamedProviderMetadata(name string) Metadata {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamedProviderMetadata", name)
	ret0, _ := ret[0].(Metadata)
	return ret0
}

// GetNamedProviderMetadata indicates an expected call of GetNamedProviderMetadata.
func (mr *MockevaluationImplMockRecorder) GetNamedProviderMetadata(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamedProviderMetadata", reflect.TypeOf((*MockevaluationImpl)(nil).GetNamedProviderMetadata), name)
}

// GetNamedProviders mocks base method.
func (m *MockevaluationImpl) GetNamedProviders() map[string]FeatureProvider {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamedProviders")
	ret0, _ := ret[0].(map[string]FeatureProvider)
	return ret0
}

// GetNamedProviders indicates an expected call of GetNamedProviders.
func (mr *MockevaluationImplMockRecorder) GetNamedProviders() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamedProviders", reflect.TypeOf((*MockevaluationImpl)(nil).GetNamedProviders))
}

// GetProvider mocks base method.
func (m *MockevaluationImpl) GetProvider() FeatureProvider {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProvider")
	ret0, _ := ret[0].(FeatureProvider)
	return ret0
}

// GetProvider indicates an expected call of GetProvider.
func (mr *MockevaluationImplMockRecorder) GetProvider() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProvider", reflect.TypeOf((*MockevaluationImpl)(nil).GetProvider))
}

// GetProviderMetadata mocks base method.
func (m *MockevaluationImpl) GetProviderMetadata() Metadata {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProviderMetadata")
	ret0, _ := ret[0].(Metadata)
	return ret0
}

// GetProviderMetadata indicates an expected call of GetProviderMetadata.
func (mr *MockevaluationImplMockRecorder) GetProviderMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProviderMetadata", reflect.TypeOf((*MockevaluationImpl)(nil).GetProviderMetadata))
}

// RemoveHandler mocks base method.
func (m *MockevaluationImpl) RemoveHandler(eventType EventType, callback EventCallback) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveHandler", eventType, callback)
}

// RemoveHandler indicates an expected call of RemoveHandler.
func (mr *MockevaluationImplMockRecorder) RemoveHandler(eventType, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveHandler", reflect.TypeOf((*MockevaluationImpl)(nil).RemoveHandler), eventType, callback)
}

// SetEvaluationContext mocks base method.
func (m *MockevaluationImpl) SetEvaluationContext(evalCtx EvaluationContext) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetEvaluationContext", evalCtx)
}

// SetEvaluationContext indicates an expected call of SetEvaluationContext.
func (mr *MockevaluationImplMockRecorder) SetEvaluationContext(evalCtx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEvaluationContext", reflect.TypeOf((*MockevaluationImpl)(nil).SetEvaluationContext), evalCtx)
}

// SetNamedProvider mocks base method.
func (m *MockevaluationImpl) SetNamedProvider(ctx context.Context, clientName string, provider FeatureProvider) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNamedProvider", ctx, clientName, provider)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetNamedProvider indicates an expected call of SetNamedProvider.
func (mr *MockevaluationImplMockRecorder) SetNamedProvider(ctx, clientName, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNamedProvider", reflect.TypeOf((*MockevaluationImpl)(nil).SetNamedProvider), ctx, clientName, provider)
}

// SetNamedProviderAndWait mocks base method.
func (m *MockevaluationImpl) SetNamedProviderAndWait(ctx context.Context, clientName string, provider FeatureProvider) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNamedProviderAndWait", ctx, clientName, provider)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetNamedProviderAndWait indicates an expected call of SetNamedProviderAndWait.
func (mr *MockevaluationImplMockRecorder) SetNamedProviderAndWait(ctx, clientName, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNamedProviderAndWait", reflect.TypeOf((*MockevaluationImpl)(nil).SetNamedProviderAndWait), ctx, clientName, provider)
}

// SetProvider mocks base method.
func (m *MockevaluationImpl) SetProvider(ctx context.Context, provider FeatureProvider) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProvider", ctx, provider)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProvider indicates an expected call of SetProvider.
func (mr *MockevaluationImplMockRecorder) SetProvider(ctx, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProvider", reflect.TypeOf((*MockevaluationImpl)(nil).SetProvider), ctx, provider)
}

// SetProviderAndWait mocks base method.
func (m *MockevaluationImpl) SetProviderAndWait(ctx context.Context, provider FeatureProvider) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProviderAndWait", ctx, provider)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProviderAndWait indicates an expected call of SetProviderAndWait.
func (mr *MockevaluationImplMockRecorder) SetProviderAndWait(ctx, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProviderAndWait", reflect.TypeOf((*MockevaluationImpl)(nil).SetProviderAndWait), ctx, provider)
}

// Shutdown mocks base method.
func (m *MockevaluationImpl) Shutdown(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockevaluationImplMockRecorder) Shutdown(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockevaluationImpl)(nil).Shutdown), ctx)
}

// MockHook is a mock of Hook interface.
type MockHook struct {
	ctrl     *gomock.Controller
	recorder *MockHookMockRecorder
	isgomock struct{}
}

// MockHookMockRecorder is the mock recorder for MockHook.
type MockHookMockRecorder struct {
	mock *MockHook
}

// NewMockHook creates a new mock instance.
func NewMockHook(ctrl *gomock.Controller) *MockHook {
	mock := &MockHook{ctrl: ctrl}
	mock.recorder = &MockHookMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHook) EXPECT() *MockHookMockRecorder {
	return m.recorder
}

// After mocks base method.
func (m *MockHook) After(ctx context.Context, hookContext HookContext, flagEvaluationDetails HookEvaluationDetails, hookHints HookHints) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "After", ctx, hookContext, flagEvaluationDetails, hookHints)
	ret0, _ := ret[0].(error)
	return ret0
}

// After indicates an expected call of After.
func (mr *MockHookMockRecorder) After(ctx, hookContext, flagEvaluationDetails, hookHints any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "After", reflect.TypeOf((*MockHook)(nil).After), ctx, hookContext, flagEvaluationDetails, hookHints)
}

// Before mocks base method.
func (m *MockHook) Before(ctx context.Context, hookContext HookContext, hookHints HookHints) (context.Context, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Before", ctx, hookContext, hookHints)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Before indicates an expected call of Before.
func (mr *MockHookMockRecorder) Before(ctx, hookContext, hookHints any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Before", reflect.TypeOf((*MockHook)(nil).Before), ctx, hookContext, hookHints)
}

// Error mocks base method.
func (m *MockHook) Error(ctx context.Context, hookContext HookContext, err error, hookHints HookHints) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", ctx, hookContext, err, hookHints)
}

// Error indicates an expected call of Error.
func (mr *MockHookMockRecorder) Error(ctx, hookContext, err, hookHints any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockHook)(nil).Error), ctx, hookContext, err, hookHints)
}

// Finally mocks base method.
func (m *MockHook) Finally(ctx context.Context, hookContext HookContext, flagEvaluationDetails HookEvaluationDetails, hookHints HookHints) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Finally", ctx, hookContext, flagEvaluationDetails, hookHints)
}

// Finally indicates an expected call of Finally.
func (mr *MockHookMockRecorder) Finally(ctx, hookContext, flagEvaluationDetails, hookHints any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Finally", reflect.TypeOf((*MockHook)(nil).Finally), ctx, hookContext, flagEvaluationDetails, hookHints)
}

// MockProvider is a mock of FeatureProvider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// BooleanEvaluation mocks base method.
func (m *MockProvider) BooleanEvaluation(ctx context.Context, flag string, defaultValue bool, flatCtx FlattenedContext) BoolResolutionDetail {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BooleanEvaluation", ctx, flag, defaultValue, flatCtx)
	ret0, _ := ret[0].(BoolResolutionDetail)
	return ret0
}

// BooleanEvaluation indicates an expected call of BooleanEvaluation.
func (mr *MockProviderMockRecorder) BooleanEvaluation(ctx, flag, defaultValue, flatCtx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BooleanEvaluation", reflect.TypeOf((*MockProvider)(nil).BooleanEvaluation), ctx, flag, defaultValue, flatCtx)
}

// FloatEvaluation mocks base method.
func (m *MockProvider) FloatEvaluation(ctx context.Context, flag string, defaultValue float64, flatCtx FlattenedContext) FloatResolutionDetail {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FloatEvaluation", ctx, flag, defaultValue, flatCtx)
	ret0, _ := ret[0].(FloatResolutionDetail)
	return ret0
}

// FloatEvaluation indicates an expected call of FloatEvaluation.
func (mr *MockProviderMockRecorder) FloatEvaluation(ctx, flag, defaultValue, flatCtx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FloatEvaluation", reflect.TypeOf((*MockProvider)(nil).FloatEvaluation), ctx, flag, defaultValue, flatCtx)
}

// Hooks mocks base method.
func (m *MockProvider) Hooks() []Hook {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hooks")
	ret0, _ := ret[0].([]Hook)
	return ret0
}

// Hooks indicates an expected call of Hooks.
func (mr *MockProviderMockRecorder) Hooks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hooks", reflect.TypeOf((*MockProvider)(nil).Hooks))
}

// IntEvaluation mocks base method.
func (m *MockProvider) IntEvaluation(ctx context.Context, flag string, defaultValue int64, flatCtx FlattenedContext) IntResolutionDetail {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntEvaluation", ctx, flag, defaultValue, flatCtx)
	ret0, _ := ret[0].(IntResolutionDetail)
	return ret0
}

// IntEvaluation indicates an expected call of IntEvaluation.
func (mr *MockProviderMockRecorder) IntEvaluation(ctx, flag, defaultValue, flatCtx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntEvaluation", reflect.TypeOf((*MockProvider)(nil).IntEvaluation), ctx, flag, defaultValue, flatCtx)
}

// Metadata mocks base method.
func (m *MockProvider) Metadata() Metadata {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Metadata")
	ret0, _ := ret[0].(Metadata)
	return ret0
}

// Metadata indicates an expected call of Metadata.
func (mr *MockProviderMockRecorder) Metadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Metadata", reflect.TypeOf((*MockProvider)(nil).Metadata))
}

// ObjectEvaluation mocks base method.
func (m *MockProvider) ObjectEvaluation(ctx context.Context, flag string, defaultValue any, flatCtx FlattenedContext) ObjectResolutionDetail {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ObjectEvaluation", ctx, flag, defaultValue, flatCtx)
	ret0, _ := ret[0].(ObjectResolutionDetail)
	return ret0
}

// ObjectEvaluation indicates an expected call of ObjectEvaluation.
func (mr *MockProviderMockRecorder) ObjectEvaluation(ctx, flag, defaultValue, flatCtx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObjectEvaluation", reflect.TypeOf((*MockProvider)(nil).ObjectEvaluation), ctx, flag, defaultValue, flatCtx)
}

// StringEvaluation mocks base method.
func (m *MockProvider) StringEvaluation(ctx context.Context, flag, defaultValue string, flatCtx FlattenedContext) StringResolutionDetail {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StringEvaluation", ctx, flag, defaultValue, flatCtx)
	ret0, _ := ret[0].(StringResolutionDetail)
	return ret0
}

// StringEvaluation indicates an expected call of StringEvaluation.
func (mr *MockProviderMockRecorder) StringEvaluation(ctx, flag, defaultValue, flatCtx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StringEvaluation", reflect.TypeOf((*MockProvider)(nil).StringEvaluation), ctx, flag, defaultValue, flatCtx)
}

// MockStateHandler is a mock of StateHandler interface.
type MockStateHandler struct {
	ctrl     *gomock.Controller
	recorder *MockStateHandlerMockRecorder
	isgomock struct{}
}

// MockStateHandlerMockRecorder is the mock recorder for MockStateHandler.
type MockStateHandlerMockRecorder struct {
	mock *MockStateHandler
}

// NewMockStateHandler creates a new mock instance.
func NewMockStateHandler(ctrl *gomock.Controller) *MockStateHandler {
	mock := &MockStateHandler{ctrl: ctrl}
	mock.recorder = &MockStateHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateHandler) EXPECT() *MockStateHandlerMockRecorder {
	return m.recorder
}

// Init mocks base method.
func (m *MockStateHandler) Init(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockStateHandlerMockRecorder) Init(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockStateHandler)(nil).Init), arg0)
}

// Shutdown mocks base method.
func (m *MockStateHandler) Shutdown(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockStateHandlerMockRecorder) Shutdown(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockStateHandler)(nil).Shutdown), arg0)
}

// MockTracker is a mock of Tracker interface.
type MockTracker struct {
	ctrl     *gomock.Controller
	recorder *MockTrackerMockRecorder
	isgomock struct{}
}

// MockTrackerMockRecorder is the mock recorder for MockTracker.
type MockTrackerMockRecorder struct {
	mock *MockTracker
}

// NewMockTracker creates a new mock instance.
func NewMockTracker(ctrl *gomock.Controller) *MockTracker {
	mock := &MockTracker{ctrl: ctrl}
	mock.recorder = &MockTrackerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTracker) EXPECT() *MockTrackerMockRecorder {
	return m.recorder
}

// Track mocks base method.
func (m *MockTracker) Track(ctx context.Context, trackingEventName string, evaluationContext EvaluationContext, details TrackingEventDetails) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Track", ctx, trackingEventName, evaluationContext, details)
}

// Track indicates an expected call of Track.
func (mr *MockTrackerMockRecorder) Track(ctx, trackingEventName, evaluationContext, details any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Track", reflect.TypeOf((*MockTracker)(nil).Track), ctx, trackingEventName, evaluationContext, details)
}
